export const reduxTypes = {
  AUTH_TOKEN: 'AUTH_TOKEN',
  RESET_DATA: 'RESET_DATA',
  THEME_MODE: 'THEME_MODE',
  LANGUAGE_CODE: 'LANGUAGE_CODE',

  // Device
  PAIRED_DEVICE: 'PAIRED_DEVICE',
  CONNECTION_STATE: 'CONNECTION_STATE',
  DEVICE_CAPABILITIES: 'DEVICE_CAPABILITIES',
  DEVICE_INFO: 'DEVICE_INFO',
  HISTORY_SYNCED_AT: 'HISTORY_SYNCED_AT',
  AUTO_RECONNECT: 'AUTO_RECONNECT',
  AUTO_RECONNECT_ENABLED: 'AUTO_RECONNECT_ENABLED',
  RECONNECT_ATTEMPT: 'RECONNECT_ATTEMPT',

  // Health data
  ADD_READINGS: 'ADD_READINGS',
  SET_LATEST_READINGS: 'SET_LATEST_READINGS',
  REMOVE_SYNCED_READINGS: 'REMOVE_SYNCED_READINGS',
  LAST_SYNC_AT: 'LAST_SYNC_AT',
};
