export const reduxTypes = {
  IS_USER_LOGIN: 'IS_USER_LOGIN',
  PROFILE_DATA: 'PROFILE_DATA',
  AUTH_TOKEN: 'AUTH_TOKEN',
  RESET_DATA: 'RESET_DATA',
  THEME_MODE: 'THEME_MODE',
  LANGUAGE_CODE: 'LANGUAGE_CODE',

  // Device
  PAIRED_DEVICE: 'PAIRED_DEVICE',
  CONNECTION_STATE: 'CONNECTION_STATE',
  DEVICE_CAPABILITIES: 'DEVICE_CAPABILITIES',

  // Health data
  ADD_READINGS: 'ADD_READINGS',
  REMOVE_SYNCED_READINGS: 'REMOVE_SYNCED_READINGS',
  LAST_SYNC_AT: 'LAST_SYNC_AT',
};
